lib/nvr_mngt_web/router.ex
defmodule NvrMngtWeb.Router do
  use NvrMngtWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NvrMngtWeb do
    pipe_through :browser # Use the default browser stack
    post "/",NvrController, :download_videos

    get "/", NvrController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", NvrMngtWeb do
  #   pipe_through :api
  # end
end

lib/nvr_mngt/application.ex
defmodule NvrMngt.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(NvrMngt.Repo, []),
      # Start the endpoint when the application starts
      supervisor(NvrMngtWeb.Endpoint, []),
      # Start your own worker by calling: NvrMngt.Worker.start_link(arg1, arg2, arg3)
      # worker(NvrMngt.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: NvrMngt.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    NvrMngtWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/nvr_mngt/repo.ex
defmodule NvrMngt.Repo do
  use Ecto.Repo, otp_app: :nvr_mngt

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/nvr_mngt_web/controllers/nvr_controller.ex
defmodule NvrMngtWeb.NvrController do
  import SweetXml

  use NvrMngtWeb, :controller
  require Logger

  def index(conn, _params) do
    render conn, "index.html"
  end

  def download_videos(conn, params) do
    IO.inspect(params)
    %{"user"=>  %{"nvrid" => nvrid,"host" => host,"port" => port,"username" => username,"password" => password,
    "channel" => channel, "starttime" => starttime, "endtime" => endtime, } }=params

      get_stream_urls("1", host, port, username, password, 1, starttime,endtime,nvrid)


    render conn, "index.html"

  end
  def download([url|urls], host, port, username, password,number,nvrid,channel) do
  #  IO.inspect(urls)
    number=number+1
    IO.inspect("loop #{number}")
    lis = tl(String.split("#{url}" ,~r/rtsp:\/\/\b[0-9]{1,3}.\b[0-9]{1,3}.\b[0-9]{1,3}.\b[0-9]{1,3}/))
    #IO.inspect(lis)
     download_stream("#{host}",  "#{port}",  "#{username}", "#{password}","#{lis}",number,nvrid,channel)
  #:timer.sleep(1000)
     download(urls, host, port, username, password,number,nvrid,channel)

  end
  def download([], host, port, username, password,number,nvrid,channel), do: nil




  def get_stream_urls(_exid, host, port, username, password, channel, starttime, endtime,nvrid) do
    IO.inspect(channel)
if channel== 20 do
   nil
else
    xml = "<?xml version='1.0' encoding='utf-8'?><CMSearchDescription><searchID>C5954E12-60B0-0001-954E-999096EF7420</searchID><trackList>"
      xml = "#{xml}<trackID>#{channel}01</trackID></trackList><timeSpanList><timeSpan><contentTypeList><contentType>video</contentType>
</contentTypeList><startTime>#{starttime}</startTime><endTime>#{endtime}</endTime>"
 xml = "#{xml}</timeSpan></timeSpanList><maxResults>600</maxResults><searchResultPostion>550</searchResultPostion><metadataList>"
    xml = "#{xml}<metadataDescriptor>//metadata.psia.org/VideoMotion</metadataDescriptor></metadataList></CMSearchDescription>"

    url = "http://#{host}:#{port}/ISAPI/ContentMgmt/search"
    case HTTPoison.post(url, xml, ["Content-Type": "application/x-www-form-urlencoded", "Authorization": "Basic #{Base.encode64("#{username}:#{password}")}", "SOAPAction": "http://www.w3.org/2003/05/soap-envelope"]) do
      {:ok, %HTTPoison.Response{body: body}} -> {:ok, body}
      { doc, _ } = body |> :binary.bin_to_list |> :xmerl_scan.string
      #[ playbackURI ] = :xmerl_xpath.string('/html/head/title', doc)
    #  IO.inspect(body)
    #result = body |> xpath(~x"//matchup/name/text()") # `sigil_x` for (x)path
  #  IO.inspect(body )
    #IO.inspect(body  |>  SweetXml.xpath(~x"//playbackURI/text()"l))
uri= body  |> SweetXml.xpath(~x"//playbackURI/text()")

    #IO.inspect(  String.split("#{uri}" ,~r/rtsp:\/\/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}/)   )
#lis = String.split("rtsp://192.168.1.200/Streaming/tracks/301/?starttime=20180728T220252Z&endtime=20180728T223107Z&name=00000002964000000&size=1064787540" ,~r/rtsp:\/\/\b[0-9]{1,3}.\b[0-9]{1,3}.\b[0-9]{1,3}.\b[0-9]{1,3}/)
  #IO.puts(tl(lis))
      download(body  |>  SweetXml.xpath(~x"//playbackURI/text()"l),host, port, username, password,0,nvrid,channel)
    #IO.inspect(body  |>  SweetXml.xpath(~x"//playbackURI/text()"l))
      _ ->

        Logger.error "[get_stream_urls] [#{url}] [#{xml}]"
        {:error}
    end
    get_stream_urls(_exid, host, port, username, password, (channel+1), starttime, endtime,nvrid)

  end

end
  def download_stream(host, port, username, password, url,number,nvrid,channel) do
      xml = "<?xml version='1.0'?><downloadRequest version='1.0' xmlns='http://urn:selfextension:psiaext-ver10-xsd'>"
      xml = "#{xml}<playbackURI>rtsp://#{host}:#{port}#{url}"
      xml = "#{xml}</playbackURI></downloadRequest>"
      root_dir="~"
      path = "#{root_dir}/nvr1/stream#{number}.mkv"
    #  File.rm(path)
      url = "http://#{host}:#{port}/PSIA/Custom/SelfExt/ContentMgmt/download"
      opts = [stream_to: self()]
      HTTPoison.post(url, xml, ["Content-Type": "application/x-www-form-urlencoded", "Authorization": "Basic #{Base.encode64("#{username}:#{password}")}", "SOAPAction": "http://www.w3.org/2003/05/soap-envelope"], opts)
      |> collect_response(self(), <<>>,number,nvrid,channel)
    end
    def collect_response(id, par, data,number,nvrid,channel) do
       receive do
         %HTTPoison.AsyncStatus{code: 200, id: id} ->
           Logger.debug "Collect response status"
           collect_response(id, par, data,number,nvrid,channel)
         %HTTPoison.AsyncHeaders{headers: _headers, id: id} ->
           Logger.debug "Collect response headers"
           collect_response(id, par, data,number,nvrid,channel)
         %HTTPoison.AsyncChunk{chunk: chunk, id: id,} ->
           save_temporary(chunk,number,nvrid,channel)
           collect_response(id, par, data,number,nvrid,channel) # <> chunk
         %HTTPoison.AsyncEnd{id: _id} ->
           Logger.debug "Stream complete"
         _ ->
           Logger.debug "Unknown message in response"
           collect_response(id, par, data,number,nvrid,channel)
       after
         5000 ->
           Logger.debug "No response after 5 seconds."
       end
     end
     defp save_temporary(chunk,number,nvrid,channel) do
       root_dir="/home/javi "
       #root_dir="/home/storage-server"

   "#{root_dir}/#{nvrid}/#{channel}/stream#{number}.mkv"
   |> File.open([:append, :binary, :raw], fn(file) -> IO.binwrite(file, chunk) end)
   |> case do
     {:error, :enoent} ->
       File.mkdir_p!("#{root_dir}/#{nvrid}/#{channel}/")
       save_temporary(chunk,number,nvrid,channel)
     _ -> :noop
   end
  end

end

lib/nvr_mngt_web/controllers/page_controller.ex
defmodule NvrMngtWeb.PageController do
  use NvrMngtWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/nvr_mngt_web/views/error_view.ex
defmodule NvrMngtWeb.ErrorView do
  use NvrMngtWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/nvr_mngt_web/views/layout_view.ex
defmodule NvrMngtWeb.LayoutView do
  use NvrMngtWeb, :view
end

lib/nvr_mngt_web/views/nvr_view.ex
defmodule NvrMngtWeb.NvrView do
  use NvrMngtWeb, :view
end

lib/nvr_mngt_web/views/page_view.ex
defmodule NvrMngtWeb.PageView do
  use NvrMngtWeb, :view
end

lib/nvr_mngt_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello NvrMngt!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/nvr_mngt_web/templates/nvr/index.html.eex
<%= form_for @conn, nvr_path(@conn, :download_videos), fn f -> %>
Enter NVR information to download videos

        <div class="row">

            <div class="col-md-2">
              <label >  NVR name   </label>
                  <%= text_input :user, :nvrid, value: "" , id: "x1"%>

              <label >  Host IP    </label>
                  <%= text_input :user, :host, value: "" , id: "x1"%>

                  <label >  Port     </label>
                      <%= text_input :user, :port, value: "", id: "y1"%>

                      <label >  Username    </label>
                          <%= text_input :user, :username, value: "", id: "x2"%>

                          <label >  Password    </label>
                              <%= text_input :user, :password, value: "", id: "y2"%>

                              <label >  channel    </label>
                                  <%= text_input :user, :channel, value: "", id: "y2"%>

                                  <label >  starttime    </label>
                                      <%= text_input :user, :starttime, value: "", id: "y2"%>


                                      <label >  endtime    </label>
                                          <%= text_input :user, :endtime, value: "", id: "y2"%>


                              <%= submit "Download" ,  class: "btn btn-default "%>



<% end %>

lib/nvr_mngt_web/templates/page/index.html.eex
<%= form_for @conn, nvr_path(@conn, :download_videos), fn f -> %>
        <div class="row">

    <!--    <%= @device.mac_addr  %>-->

    <!--    <%=  IO.inspect(String.slice(@device.mac_addr, -6..-1)) %>-->
            <div class="col-md-4">
              <label >  X1    </label>
                  <%= text_input :user, :x1, value: "" , id: "x1"%>

                  <label >  Y1    </label>
                      <%= text_input :user, :y1, value: "", id: "y1"%>

                      <label >  X2    </label>
                          <%= text_input :user, :x2, value: "", id: "x2"%>

                          <label >  Y2    </label>
                              <%= text_input :user, :y2, value: "", id: "y2"%>
                              <%= submit "Set Mask" ,  class: "btn btn-default "%>



<% end %>